-- CREAR BASE DE DATOS
CREATE DATABASE estudiantes_db;
-- CREACION TABLA
CREATE TABLE estudiantes (nombre VARCHAR(50) NOT NULL, rut VARCHAR(12) PRIMARY KEY NOT NULL, CURSO VARCHAR(50) NOT NULL, nivel SMALLINT NOT NULL),

